#
#  LTICTR imgaes update to 1.4.2
#
# Usage
# 1. change FROM line
# 2. execute docker build command
# ex.) docker build . --format=docker -f Dockerfile.ltictr_update -t jupyterhub-ltictr/singleuser:2025xxxx
#

#FROM ghcr.io/jupyter-fumihax/jupyterhub-ltictr.singleuser
#FROM ghcr.io/jupyter-fumihax/jupyterhub-ltictr.base-notebook
#FROM ghcr.io/jupyter-fumihax/jupyterhub-ltictr.scipy-notebook
#FROM ghcr.io/jupyter-fumihax/jupyterhub-ltictr.tensorflow-notebook
#FROM ghcr.io/jupyter-fumihax/jupyterhub-ltictr.datascience-notebook
#FROM ghcr.io/jupyter-fumihax/jupyterhub-ltictr.php-notebook
#FROM ghcr.io/jupyter-fumihax/jupyterhub-ltictr.java-notebook
#FROM ghcr.io/jupyter-fumihax/jupyterhub-ltictr.rust-notebook
#FROM ghcr.io/jupyter-fumihax/jupyterhub-ltictr.xeus-ijs
#FROM ghcr.io/jupyter-fumihax/jupyterhub-ltictr.xeus-cling
#FROM ghcr.io/jupyter-fumihax/jupyterhub-ltictr.vhtec-notebook
#FROM ghcr.io/jupyter-fumihax/jupyterhub-ltictr.swift-tensorflow
#FROM ghcr.io/jupyter-fumihax/jupyterhub-ltictr.devel-notebook
#FROM ghcr.io/jupyter-fumihax/jupyterhub-ltictr.jupyterlab-broccoli
FROM ghcr.io/jupyter-fumihax/jupyterhub-ltictr.jupyterlab-broccoli-tensorflow

#FROM ghcr.io/jupyter-fumihax/jupyterhub-ltictr.cuda-ubuntu20
#FROM ghcr.io/jupyter-fumihax/jupyterhub-ltictr.base-notebook-gpu
#FROM ghcr.io/jupyter-fumihax/jupyterhub-ltictr.tensorflow-notebook-gpu
#FROM ghcr.io/jupyter-fumihax/jupyterhub-ltictr.scipy-notebook-gpu


USER root

############################################

# Jupyter Notice
RUN pip install --no-cache-dir jnotice

#
# Lticontainer
HEALTHCHECK CMD /usr/local/bin/health_check.sh

#COPY \
#    bin/start.sh \
    bin/submit \
#    bin/health_check.sh \
    /usr/local/bin/

#COPY \
#    etc/.bashrc \
#    /root/

#COPY \
#    etc/.bashrc \
#    /etc/skel/

# for Pluto
#COPY \
#    etc/jupyter_server_config.py \
#    /etc/jupyter

# for Broccoli
# とりあえず使わないし xPython とか混乱するので，今は削除しておく．
RUN  set -eux \
 && rm -rf  /opt/conda/share/jupyter/kernels/xpython \
 && rm -rf  /opt/conda/share/jupyter/kernels/xpython-raw \
 && true

#
RUN set -eux \
## && rm -f /usr/local/bin/actlimit_check.sh \
 && chmod a+rx /usr/local/bin/* \
# && chmod a+r  /etc/jupyter/* \
 && true


#CMD ["start-notebook.sh"]
