# Start from S4TF base image
#FROM gcr.io/swift-tensorflow/base-deps-cuda10.2-cudnn7-ubuntu18.04
#FROM gcr.io/swift-tensorflow/base-deps-cuda11.0-cudnn8-ubuntu18.04
#FROM gcr.io/swift-tensorflow/base-deps-ubuntu18.04
FROM gcr.io/swift-tensorflow/base-deps-ubuntu20.04

USER root

#
RUN apt-get update \
 && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
    sudo \
    binutils \
    apt-utils \
    git \
    libfreetype6-dev\
    openssl \
    libssl-dev \
    clang \
    libpython3-dev \
    libblocksruntime-dev \
    language-pack-ja-base \
    language-pack-ja \
 && apt-get -y clean \
 && rm -rf /var/lib/apt/lists/* \
 && true

#
# Allow the caller to specify the toolchain to use
#ARG swift_tf_url=https://storage.googleapis.com/swift-tensorflow-artifacts/nightlies/latest/swift-tensorflow-DEVELOPMENT-cuda10.2-cudnn7-ubuntu18.04.tar.gz
#ARG swift_tf_url=https://storage.googleapis.com/swift-tensorflow-artifacts/nightlies/latest/swift-tensorflow-DEVELOPMENT-stock-ubuntu20.04.tar.gz
#ARG swift_tf_url=https://storage.googleapis.com/swift-tensorflow-artifacts/releases/v0.13/swift-tensorflow-RELEASE-0.13-ubuntu18.04.tar.gz
ARG swift_tf_url=https://storage.googleapis.com/swift-tensorflow-artifacts/releases/v0.13/swift-tensorflow-RELEASE-0.13-ubuntu20.04.tar.gz

#
# Download and extract S4TF
WORKDIR /
ADD $swift_tf_url swift.tar.gz
RUN tar -xzf swift.tar.gz --directory=usr --strip-components=1 \
 && rm swift.tar.gz \
 && git clone https://github.com/google/swift-jupyter.git \
 && update-locale LANG=ja_JP.UTF-8 \
 && true

#
# Install some python libraries that are useful to call from swift
WORKDIR /swift-jupyter
RUN echo "pillow" >> docker/requirements_py_graphics.txt \
 && python3 -m pip install --no-cache-dir -r docker/requirements.txt \
 && python3 -m pip install --no-cache-dir -r docker/requirements_py_graphics.txt \
 && python3 register.py --sys-prefix --swift-toolchain  / > /dev/null \
 && chmod a+r * \
 && true

#
# Anaconda
ENV CONDA_HOME=/opt/conda
ENV PATH=$CONDA_HOME/bin:/usr/local/bin:$PATH

ARG miniconda_url=https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh 
#ARG miniconda_url=https://repo.anaconda.com/miniconda/Miniconda3-py310_23.5.2-0-Linux-x86_64.sh 
#ARG miniconda_url=https://repo.anaconda.com/miniconda/Miniconda3-py39_23.5.2-0-Linux-x86_64.sh 

ADD $miniconda_url  miniconda.sh

RUN bash miniconda.sh -b -p $CONDA_HOME \
 && rm  miniconda.sh 

RUN $CONDA_HOME/bin/conda update  -n base  conda -y \
 && $CONDA_HOME/bin/conda install --prefix $CONDA_HOME -c conda-forge jupyterhub -y \
 && $CONDA_HOME/bin/conda install --prefix $CONDA_HOME -c conda-forge jupyterlab -y \
 && $CONDA_HOME/bin/conda install --prefix $CONDA_HOME -c conda-forge jupyterlab_widgets -y \
 && $CONDA_HOME/bin/conda install --prefix $CONDA_HOME -c conda-forge jupyterlab-language-pack-ja-jp -y \
 && $CONDA_HOME/bin/conda install --prefix $CONDA_HOME -c conda-forge jupyterhub-singleuser -y \
 && $CONDA_HOME/bin/conda clean   --all -y \
 && true


# LTIContainer
ADD \
    bin/start.sh \
    bin/start-notebook.sh \
    bin/start-singleuser.sh \
    bin/commit.sh \
    bin/ipynb_conv \
    bin/ipynb_conv_alt \
    bin/ipynb_conv_alt.py \
    bin/ipynb_deploy \
    bin/ipynb_setup \
    bin/ipynb_submit \
    bin/submit \
    bin/ipynb_extract \
    bin/extract \
    bin/ipynb_tocsv \
    bin/tocsv \
    /usr/local/bin/

ADD \
    etc/.bashrc \
    etc/.bash_profile \
    etc/.vimrc \
    /root/

ADD \
    etc/.bash_profile \
    etc/.bashrc \
    etc/.vimrc \
    /etc/skel/

ADD \
    etc/passwd.orig \
    etc/group.orig \
    /etc/

RUN chmod a+rx /usr/local/bin/* \
 && chmod a+r  /etc/skel/.vimrc /etc/skel/.bash* \
 && true

CMD ["start-notebook.sh"]
