#
# Usage
# 1. cahge FROM line
# 2. execute docker build command
# ex.) cd .. 
#      docker build . -t jupyterhub-ltids/jupyter-base-gpu:3.6.5 --format=docker -f dockerfile/Dockerfile.gpu
#

# https://hub.docker.com/r/nvidia/cuda/tags
FROM docker.io/nvidia/cuda:12.2.0-base-ubuntu20.04

USER root


RUN apt-get update \
## && apt-get upgrade -y \
 && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
    wget \
    sudo \
    python3-pycuda \
#    binutils \
#    apt-utils \
#    tini \
#    g++ \
#    vim \
#    git \
    language-pack-ja-base \
    language-pack-ja \
 && apt-get -y clean \
 && rm -rf /var/lib/apt/lists/* \
 && true


RUN wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh \
 && bash Miniconda3-latest-Linux-x86_64.sh -b -p /opt/conda \
 && rm Miniconda3-latest-Linux-x86_64.sh 

# python 3.10
#RUN wget https://repo.anaconda.com/miniconda/Miniconda3-py310_23.5.2-0-Linux-x86_64.sh \
# && bash Miniconda3-py310_23.5.2-0-Linux-x86_64.sh -b -p /opt/conda \
# && rm   Miniconda3-py310_23.5.2-0-Linux-x86_64.sh 


RUN /opt/conda/bin/conda update  -n base conda -y \
 && /opt/conda/bin/conda install --prefix /opt/conda -c conda-forge notebook -y \
 && /opt/conda/bin/conda install --prefix /opt/conda -c conda-forge jupyter -y \
 && /opt/conda/bin/conda install --prefix /opt/conda -c conda-forge jupyterhub -y \
 && /opt/conda/bin/conda install --prefix /opt/conda -c conda-forge jupyterlab -y \
 && /opt/conda/bin/conda install --prefix /opt/conda -c conda-forge jupyterlab_widgets -y \
 && /opt/conda/bin/conda install --prefix /opt/conda -c conda-forge jupyterlab-language-pack-ja-jp -y \
 && /opt/conda/bin/conda install --prefix /opt/conda -c conda-forge jupyterhub-singleuser -y \
 && /opt/conda/bin/conda install --prefix /opt/conda -c conda-forge pillow -y \
 && /opt/conda/bin/conda install --prefix /opt/conda pip -y \
# && /opt/conda/bin/conda update  --prefix /opt/conda --all -y \
 && /opt/conda/bin/conda clean   --all -y \
 && /opt/conda/bin/pip   install --prefix /opt/conda ipynb_path \
 && true

RUN true \
 && /opt/conda/bin/conda install --prefix /opt/conda -c conda-forge tensorflow=*=gpu_* -y \
 && /opt/conda/bin/conda install --prefix /opt/conda -c conda-forge matplotlib -y \
 && /opt/conda/bin/conda install --prefix /opt/conda -c conda-forge pandas -y \
 && /opt/conda/bin/conda install --prefix /opt/conda -c conda-forge numpy -y \
#  && /opt/conda/bin/pip   install --prefix /opt/conda PyCUDA \
 && true

#RUN /opt/conda/bin/conda install --prefix /opt/conda -c conda-forge scikit-learn-intelex -y


ADD \
    bin/start.sh \
    bin/start-notebook.sh \
    bin/start-singleuser.sh \
    bin/commit.sh \
    bin/ipynb_conv \
    bin/ipynb_conv_alt \
    bin/ipynb_conv_alt.py \
    bin/ipynb_deploy \
    bin/ipynb_setup \
    bin/ipynb_submit \
    bin/submit \
    bin/ipynb_extract \
    bin/extract \
    bin/ipynb_tocsv \
    bin/tocsv \
    /usr/local/bin/

ADD \
    etc/.bashrc \
    etc/.bash_profile \
    etc/.vimrc \
    /root/

ADD \
    etc/.bash_profile \
    etc/.bashrc \
    etc/.vimrc \
    /etc/skel/

ADD \
    etc/passwd.orig \
    etc/group.orig \
    /etc/

RUN chmod a+rx /usr/local/bin/* \
 && chmod a+r  /etc/skel/.vimrc /etc/skel/.bash* \
 && true


CMD ["start-notebook.sh"]
