#
# docker build . --format=docker -f Dockerfile.dev -t jupyterhub-ltictr/dev-notebook:xxx
#

FROM docker.io/jupyterhub/singleuser

USER root

RUN apt-get update \
# && apt-get upgrade -y \
 && apt-get install -y --no-install-recommends \
    git \
    binutils \
    apt-utils \
    language-pack-ja-base \
    language-pack-ja \
    vim \
    mlocate \
 && apt-get -y clean \
 && rm -rf /var/lib/apt/lists/* \
 && true


ENV CONDA_HOME=/opt/conda
ENV PATH=$CONDA_HOME/bin:$PATH

RUN $CONDA_HOME/bin/conda update  -n base conda \
 && $CONDA_HOME/bin/conda update  --prefix $CONDA_HOME -c conda-forge python -y \
 && $CONDA_HOME/bin/conda update  --prefix $CONDA_HOME -c conda-forge ipykernel -y \
 && $CONDA_HOME/bin/conda update  --prefix $CONDA_HOME -c conda-forge nodejs -y \
 && $CONDA_HOME/bin/conda update  --prefix $CONDA_HOME -c conda-forge jupyterhub -y \
 && $CONDA_HOME/bin/conda update  --prefix $CONDA_HOME -c conda-forge jupyterlab -y \
 && $CONDA_HOME/bin/conda install --prefix $CONDA_HOME -c conda-forge jupyterlab_widgets -y \
 && $CONDA_HOME/bin/conda install --prefix $CONDA_HOME -c conda-forge jupyterlab-language-pack-ja-jp -y \
 && $CONDA_HOME/bin/conda install --prefix $CONDA_HOME -c conda-forge jupyterhub-singleuser -y \
 && $CONDA_HOME/bin/conda install --prefix $CONDA_HOME -c conda-forge mamba -y \
 && $CONDA_HOME/bin/conda install --prefix $CONDA_HOME -c conda-forge pre-commit -y \
 && $CONDA_HOME/bin/conda install --prefix $CONDA_HOME -c conda-forge jupyter-packaging -y \
 && $CONDA_HOME/bin/conda install --prefix $CONDA_HOME -c conda-forge cookiecutter -y \
 && $CONDA_HOME/bin/conda install --prefix $CONDA_HOME -c conda-forge pip -y \
 && $CONDA_HOME/bin/pip   install --upgrade jupyterhub-ltiauthenticator \
 && true

#
RUN $CONDA_HOME/bin/conda install --prefix $CONDA_HOME -c conda-forge -y jupytext 
RUN $CONDA_HOME/bin/conda install --prefix $CONDA_HOME -c conda-forge -y jupyterlab-lsp 'python-lsp-server[all]' 
RUN $CONDA_HOME/bin/conda install --prefix $CONDA_HOME -c conda-forge -y ipycanvas

RUN $CONDA_HOME/bin/pip install jupyterlab-tabular-data-editor


####################################################################################

#
# blockly
#
RUN $CONDA_HOME/bin/conda install --prefix $CONDA_HOME -c conda-forge -y \
    nodejs=18 \
    jupyterlab==3.6.* \
    xeus-python==0.15.7 \
    xeus-lua 

RUN true \
 && mkdir -p /opt/devel && cd /opt/devel \
 && git clone https://github.com/QuantStack/jupyterlab-blockly.git \
 && cd jupyterlab-blockly/ \
 && pre-commit install \
 && pip install -e ".[dev]" \
 && jupyter labextension develop . --overwrite \
 && jlpm build \
# && jupyter lab build --minimize=False \
 && chmod -R a+r /opt/devel && find /opt/devel -type d | xargs chmod a+x \
 && true


#
RUN $CONDA_HOME/bin/conda clean   --all -y


####################################################################################

#
# Lticontainer
HEALTHCHECK CMD /usr/local/bin/actlimit_check.sh

ADD \
    bin/start.sh \
    bin/start-notebook.sh \
    bin/start-singleuser.sh \
    bin/commit.sh \
    bin/ipynb_conv \
    bin/ipynb_conv_alt \
    bin/ipynb_conv_alt.py \
    bin/ipynb_deploy \
    bin/ipynb_setup \
    bin/ipynb_submit \
    bin/submit \
    bin/ipynb_extract \
    bin/extract \
    bin/ipynb_tocsv \
    bin/tocsv \
    bin/actlimit_check.sh \
    /usr/local/bin/

ADD \
    etc/.bashrc \
    etc/.bash_profile \
    etc/.vimrc \
    /root/

ADD \
    etc/.bash_profile \
    etc/.bashrc \
    etc/.vimrc \
    /etc/skel/

ADD \
    etc/passwd.orig \
    etc/group.orig \
    /etc/
 
RUN chmod a+rx /usr/local/bin/* \
 && chmod a+r  /etc/skel/.vimrc /etc/skel/.bash* \
 && true

