#!/bin/sh

LANG=C

LINUX_TOP=.
#WIN_TOP=../JunkBox_Lib++
WIN_TOP=../../../vc++/JunkBox_Lib++


BASICLIB_CPP=`(cd $LINUX_TOP && ls BasicLib/*.cpp)`
BASICLIB_H=`(cd $LINUX_TOP && ls BasicLib/*.h)`

EXTENDLIB_CPP=`(cd $LINUX_TOP && ls ExtendLib/*.cpp)`
EXTENDLIB_H=`(cd $LINUX_TOP && ls ExtendLib/*.h)`

GRAPHLIB_CPP=`(cd $LINUX_TOP && ls GraphLib/*.cpp)`
GRAPHLIB_H=`(cd $LINUX_TOP && ls GraphLib/*.h)`

BREPLIB_CPP=`(cd $LINUX_TOP && ls BREPLib/*.cpp)`
BREPLIB_H=`(cd $LINUX_TOP && ls BREPLib/*.h)`

MATHLIB_CPP=`(cd $LINUX_TOP && ls MathLib/*.cpp)`
MATHLIB_H=`(cd $LINUX_TOP && ls MathLib/*.h)`

NILIB_CPP=`(cd $LINUX_TOP && ls NiLib/*.cpp)`
NILIB_H=`(cd $LINUX_TOP && ls NiLib/*.h)`

MESHLIB_CPP=`(cd $LINUX_TOP && ls MeshLib/*.cpp)`
MESHLIB_H=`(cd $LINUX_TOP && ls MeshLib/*.h)`

BASICLIB_LIB_C=`(cd $LINUX_TOP && ls BasicLib/Lib/*.c)`
BASICLIB_LIB_H=`(cd $LINUX_TOP && ls BasicLib/Lib/*.h)`

EXTENDLIB_XLIB_C=`(cd $LINUX_TOP && ls ExtendLib/xLib/*.c)`
EXTENDLIB_XLIB_H=`(cd $LINUX_TOP && ls ExtendLib/xLib/*.h)`



copy2linux()
{
    WF=$WIN_TOP/$1
    LF=$LINUX_TOP/$2

    if [ ! -f $WF ]; then
        return
    fi

    nkf -wd $WF >| $LF
    echo "update "$LF
}



diffwin()
{
    LF=$LINUX_TOP/$1
    WF=$WIN_TOP/$1

    if [ ! -f $WF ]; then
        return
    fi

    nkf -wd $WF >| $WF.temp
    diff -q $LF $WF.temp |awk -F" " '{print $2}'
    rm -rf $WF.temp
}


diffwin_c()
{
    LF=$LINUX_TOP/$1
    WF=`echo $WIN_TOP/$1 | sed s/\.c$/\.cpp/`

    if [ ! -f $WF ]; then
        return
    fi

    nkf -wd $WF >| $WF.temp
    diff -q $LF $WF.temp |awk -F" " '{print $2}'
    rm -rf $WF.temp
}


diffwin_all()
{
    for LN in $MESHLIB_H   $NILIB_H   $MATHLIB_H   $EXTENDLIB_H   $BASICLIB_H   $GRAPHLIB_H   $BREPLIB_H ; do
        #echo $LN
        diffwin $LN
    done

    for LN in $MESHLIB_CPP $NILIB_CPP $MATHLIB_CPP $EXTENDLIB_CPP $BASICLIB_CPP $GRAPHLIB_CPP $BREPLIB_CPP ; do
        #echo $LN
        diffwin $LN
    done

    for LN in $BASICLIB_LIB_H $EXTENDLIB_XLIB_H ; do
        #echo $LN
        diffwin $LN
    done

    for LN in $BASICLIB_LIB_C $EXTENDLIB_XLIB_C ; do
        diffwin_c $LN
    done
}



for LN in `diffwin_all` ; do
    WN=`echo $LN | sed s/\.c$/\.cpp/`
    copy2linux $WN $LN
done




